### ISSUE TITLE
Where is dconfig.properties?

### ISSUE THREAD

**Issue by murdonson** [ldscc/StableMA#2]
感觉错误好多 运行不起来

**Comment by murdonson** [comment]
![image](https://user-images.githubusercontent.com/20641803/27251690-86408120-537e-11e7-91cd-981d8f0f59a5.png)

**Comment by murdonson** [comment]
I did not prepare data.(⊙o⊙)

**Comment by cchao0116** [comment]
Hi there,
Sorry for my late response first.
Many change has been committed recently, but the README file was not correspondingly updated.
Sorry again.


Currently, the right routine to run the program is as follows:
1. Download the Movielens 1M/10M from [GroupLens](https://grouplens.org/datasets/movielens/):
For example you unzip 10M dataset at C:/10M, i.e.,g you have "C:/10M/ratings.dat"
2. Then run the prepare_data.py to generate the 5 folds of training and testing data :
For example, run command "./prepare_data C:/10M/", then the training/testing data will be in folder "C:/10M/1/", ..., "C:/10M/5/"
3. After preparing the data, you can run any test case in "src/test/java/code/sma/recmmd". Prior to that, you still need to configure the path of the generated data mentioned in STEP 2:
For example, in "src/main/resources/samples/WEMAREC.properties", change $ROOT_DIRs to C:/10M/1/.
4. All the results will be showed in service-core/service-normal.log files under folder "./logs". Additionally, you can change them to anyplace you want. The configure file is in "/src/main/resources/log4j.properties"




I wish it works for you, enjoy it.

**Comment by murdonson** [comment]
Actually I figure it out myself before you notice it.Thanks anyway(づ￣ 3￣)づ
