### ISSUE TITLE
Where is the GLOMA.properties?

### ISSUE THREAD

**Issue by VodkaChen** [ldscc/StableMA#3]
Hi! 
I have read your paper<GLOMA Embedding Global Information in Local Matrix Approximation Models for Collaborative Filtering>,and I want to run the GLOMA model，but I don't know how to run ,could you tell me about it?
Thank you !

**Comment by cchao0116** [comment]
You can find the test case in the dev branch:
StableMA/src/test/java/code/sma/recmmd/cf/ma/ensemble/MTRECTest.java
