### ISSUE TITLE
How do we use K-means clustering for sparse rating matrix?

### ISSUE THREAD

**Issue by 458138584** [ldscc/StableMA#4]
Ignore the 0 when calculating the distance between two rows  ?
eg.
[1 0 3 4
 0 2 1 2]
Thank you.

**Comment by cchao0116** [comment]
I don't think Euclidean distance is a good metric for sparse data, how about cosine? Pearson similarity?

Suppose SparseMatrix is used to store the data and every row is denoted as a data sample:

Ignoring 0s in [here](https://github.com/ldscc/StableMA/blob/f9e5f8fab45c5ed1b948b2cb371cccc8fa7968f8/src/main/java/code/sma/core/impl/SparseVector.java#L491)

```
double cosine(SparseVector s1, SparseVector s2):
             double dot = s1. innerProduct(s2);
             return dot/(s1.norm() * s2.norm())
```
